<<<<<<< HEAD
=======
# Not too sure about the payment side
# check dburl if they are correct
# AMQP side of MS, how should I do it?
# place an order ms also not sure
# ask about the names of the image eg activity_log VS activity, must it be the same?
# need to include the build portion

>>>>>>> c796eaf1976b442f37001b20113cb022bfa21729
version: "3.8"

volumes:
  rabbitmq_data:

services:
<<<<<<< HEAD
  ###################################
  # Order: The Order microservice
  ###################################
  order:
    build:
      context: ./
      dockerfile: order.Dockerfile
    image: jolenechew/order:esd
    restart: always
    environment:
      dburl: mysql+mysqlconnector://is213@host.docker.internal:3306/order
      PYTHONUNBUFFERED: 1

  ###################################
  # Mystery Box: The Mystery Box microservice
  ###################################
  box:
    build:
      context: ./
      dockerfile: box.Dockerfile
    image: jolenechew/box:esd
    restart: always
    environment:
      dburl: mysql+mysqlconnector://is213@host.docker.internal:3306/box
      PYTHONUNBUFFERED: 1

  ###################################
  # Payment: The Payment microservice
  ###################################
  payment:
    build:
      context: ./
      dockerfile: payment.Dockerfile
    image: jolenechew/payment:esd
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
=======

#################################################### AMQP's Microservices ####################################################
>>>>>>> c796eaf1976b442f37001b20113cb022bfa21729

  ####################################
  # RabbitMQ: The messaging broker   
  ####################################
  rabbitmq:
    image: rabbitmq:3-management
    hostname: esd-rabbit
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes: 
      - rabbitmq_data:/var/lib/rabbitmq

  #################################################
<<<<<<< HEAD
=======
  # Activity Log: The Activity Log microservice
  #################################################
  activity_log:
    build:
      context: ./
      dockerfile: activity_log.Dockerfile
    image: esdProj/activity_log:esd
    restart: always
    depends_on:
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1

  ######################################
  # Notification: The Notification microservice
  ######################################
  notification:
    build:
      context: ./
      dockerfile: notifications.Dockerfile
    image: esdProj/notification:esd
    restart: always
    depends_on:
      - rabbitmq
    environment:

  ######################################
  # Error: The Error microservice
  ######################################
  error:
    build:
      context: ./
      dockerfile: error.Dockerfile
    image: esdProj/error:esd
    restart: always
    depends_on:
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1

  ##################################################
  # payment: The payment microservice
  ##################################################
  payment:
    build:
      context: ./
      dockerfile: payment.Dockerfile
    image: esdProj/payment:esd
    restart: always
    environment:
      PYTHONUNBUFFERED: 1

############################################ Invocation based's Microservices #################################################

  ####################################
  # Box: The Mystery Box microservice
  ####################################
  box:
    build:
      context: ./
      dockerfile: box.Dockerfile
    image: esdProj/box:esd
    restart: always
    environment:
      dburl: mysql+mysqlconnector://is213@host.docker.internal:3306/box
      PYTHONUNBUFFERED: 1
    ports:
      - "5000:5000"

  ##########################################
  # Restaurant: The Restaurant microservice
  ##########################################
  restaurant:
    build:
        context: ./
        dockerfile: restaurant.Dockerfile
    image: esdProj/restaurant:esd
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/restaurant
      restURL: http://localhost:5300/restaurant
    ports:
      - "5300:5300"

  ########################################
  # Location: The Location microservice
  ########################################
  location:
    build:
        context: ./
        dockerfile: location.Dockerfile
    image: esdProj/location:esd
    restart: always
    environment:
      locationURL: http://localhost:5200/location
      PYTHONUNBUFFERED: 1

  ###################################
  # Nearby: The Nearby microservice
  ###################################
  nearby:
    build:
        context: ./
        dockerfile: nearby.Dockerfile
    image: esdProj/nearby:esd
    depends_on:
      - location
      - box
      - restaurant
      - activity_log
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      nearbyURL: http://localhost:5100/near_by
      PYTHONUNBUFFERED: 1
    ports:
      - "5100:5100"

  ##################################################
  # order: The order microservice
  ##################################################
  order:
    build:
      context: ./
      dockerfile: order.Dockerfile
    image: esdProj/order:esd
    restart: always
    environment:
      dburl: mysql+mysqlconnector://is213@host.docker.internal:3306/order
      PYTHONUNBUFFERED: 1

  ##################################################
  # Cancel an order: The cancel_order microservice
  ##################################################
  cancel_order:
    build:
        context: ./
        dockerfile: cancel_order.Dockerfile
    image: esdProj/cancel_order:esd
    depends_on:
      - box
      - order
      - activity_log
      - notification
      - error
      - payment
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      order_URL: http://order:5001/order
      box_URL: "http://localhost:6000/box"
      payment_URL: "http://localhost:6002/create-checkout-session"
      PYTHONUNBUFFERED: 1
    ports:
      - "5500:5500"

  #################################################
>>>>>>> c796eaf1976b442f37001b20113cb022bfa21729
  # Place an Order: The Place an Order microservice
  #################################################
  place_order:
    build:
      context: ./
      dockerfile: place_order.Dockerfile
<<<<<<< HEAD
    image: jolenechew/place_order:esd
=======
    image: esdProj/place_order:esd
>>>>>>> c796eaf1976b442f37001b20113cb022bfa21729
    restart: always
    depends_on:
      - order
      - box
      - payment
      - activity_log
      - error
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      order_URL: http://order:5001/order
      box_URL: "http://localhost:6000/box"
      payment_URL: "http://localhost:6002/create-checkout-session"
      PYTHONUNBUFFERED: 1
    ports:
<<<<<<< HEAD
      - "5100:5100"

  #################################################
  # Activity Log: The Activity Log microservice
  #################################################
  activity_log:
    build:
      context: ./
      dockerfile: activity_log.Dockerfile
    image: jolenechew/activity_log:esd
    restart: always
    depends_on:
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1

  ###################################
  # Error: The Error microservice
  ###################################
  error:
    build:
      context: ./
      dockerfile: error.Dockerfile
    image: jolenechew/error:esd
    restart: always
    depends_on:
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1



  
=======
      - "5100:5100"
>>>>>>> c796eaf1976b442f37001b20113cb022bfa21729
